name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: wyvox/action@v1
      - run: pnpm lint


  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: wyvox/action@v1
      - run: pnpm test

  DeployProduction:
    name: "Deploy: Production"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [test]
    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        app:
        - { path: "./dist", cloudflareName: "turborepo-summary-analyzer", name: "App" }

    steps:
      - uses: wyvox/action@v1
      - run: pnpm build
      - name: Publish ${{ matrix.app.name }}
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ matrix.app.cloudflareName }}
          directory: ${{ matrix.app.path }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

